types:
  - build

before_script:
  - export BUILD_ID=${CI_BUILD_REF:0:7}

build: 
  script:
    - docker build -t "munnerz/blog-build:$BUILD_ID" .
    - docker tag -f "munnerz/blog-build:$BUILD_ID" "registry.marley.xyz/munnerz/blog-build:$BUILD_ID"
    - docker tag -f "munnerz/blog-build:$BUILD_ID" "registry.marley.xyz/munnerz/blog-build:latest"
    - docker push "registry.marley.xyz/munnerz/blog-build:$BUILD_ID"
    - docker push "registry.marley.xyz/munnerz/blog-build:latest"
  type: build
  only: 
    - master
  tags: 
    - build